sudo: false
language: ruby
cache: bundler

addons:
  apt:
    packages:
    - libarchive12
    - libarchive-dev

matrix:
  include:
    - rvm: 2.1.9
    - rvm: 2.2.5
    - rvm: 2.3.1
  allow_failures:
    - rvm: 2.3.1

script: bundle exec rake spec
